#!/bin/sh

export BIBFILES="$(fd --follow --no-ignore -e bib)"
if ! test "$BIBFILES"; then
    echo "No biblatex files" >&2
    exit 1
fi

cat $BIBFILES | grep '^@' |
    sed 's,^[^{]*{,,g' | sed 's/, *$//g' | sort -u |  # Get citekeys
    fzf -m -q "$(echo $@)" -1 \
        --inline-info --preview-window=up \
        --tabstop=4 --preview='CITEKEY={}
        PATTERN="@.*{$CITEKEY, *"
        grep -l "$PATTERN" $BIBFILES
        echo ------------------------------ | cut -c1-$COLUMNS
        echo
        grep -h -A 3 "$PATTERN" $BIBFILES' |
    sed "s/^/@/g" | sed "s/$/;/g" |         # Add separators
    tr "\n" " " |                           # Join lines
    rev | cut -c3- | rev                    # Trim last separator
