#!/bin/sh

BIBFILES=""; CURDIR=.; while true; do
    NEWFILES="$(find $CURDIR -maxdepth 1 -name '*.bib'|sed 's,^\./,,')"
    test "$NEWFILES" && BIBFILES="$BIBFILES $NEWFILES"
    test "$(realpath $CURDIR)" = / && break
    if test $CURDIR = .; then CURDIR=..; else CURDIR=../$CURDIR; fi
done; export BIBFILES

if ! test "$BIBFILES"; then
    echo "No biblatex files" >&2
    exit 1
fi

cat $BIBFILES | grep '^@' |
    sed 's,^[^{]*{,,g' | sed 's/, *$//g' | sort -u |  # Get citekeys
    fzf -e -m -q "$(echo $@)" -1 \
        --inline-info --preview-window=up \
        --tabstop=4 --preview='CITEKEY={}
        PATTERN="@.*{$CITEKEY, *"
        grep -l "$PATTERN" $BIBFILES
        echo ------------------------------ | cut -c1-$COLUMNS
        echo
        grep -h -A 3 "$PATTERN" $BIBFILES' |
    sed "s/^/@/g" | sed "s/$/;/g" |         # Add separators
    tr "\n" " " |                           # Join lines
    rev | cut -c3- | rev                    # Trim last separator
